### ISSUE TITLE
It would be nice if you add 3day or weekly weather forecast

### ISSUE THREAD

**Issue by ghost** [psipika/lxweather#1]
Hello! Is it possible if you add 3day or weekly weather forecast for the lxweather?

Thanks in advance

**Comment by psipika** [comment]
I think that can be arranged ;). I'll take a look to see what needs to be done. Thanks for the comment!

**Comment by ghost** [comment]
This would be a great feature for those who used similar programs from *buntu ppa's like indicator-weather and this will provide 3day or weekly weather forecasts! Thank you for considering this request! Much appreciated!

**Comment by psipika** [comment]
Currently working on this, the forecast provides 5 days and that's what I'll try to provide.

**Comment by psipika** [comment]
Fixed with commit 3bd614c975d2f09a1ddf7efdf8f48c1d39035f53.
