### ISSUE TITLE
lxweather search cannot find the exact location from yahoo weather

### ISSUE THREAD

**Issue by ghost** [psipika/lxweather#3]
Hello! There is been another issue I came across when I select my location for example Paradeisi which is in Rodos (Greece) but it doesn't show the exact location Paradeisi and it stuck in other locations near Rodos (Greece), but I managed to get a copy of the configuration file backed up the original and I pasted the location code and the state name from yahoo weather, is there anyway to fix this search? so the yahoo weather can find it without having to do this by hand? I hope this is informative! again! thanks in advance!

**Comment by psipika** [comment]
I'll need to verify yahoo can provide your location using the select query I'm invoking.  What was the reason for closing the issue?

**Comment by psipika** [comment]
I did a bit of testing and it seems that the app is showing City, State and Country.
I don't know if you're looking for the app to go in deeper (looks like Paradeisi is the neighborhood).
I don't know if that's something that can be determined in a generic fashion...
Not sure if you tried this:
Got to [yahoo weather developer page](https://developer.yahoo.com/weather/#examples=) and in the `YQL Console` type this in: `select * from geo.placefinder where text="paradeisi"`, then click on `Test`.  This will show you exactly what the app gets...

**Comment by ghost** [comment]
I did closed that issue because it was from last year and i didn't get any info but anyway... Thanks for the input and I will try and give it a shot!
